#!/usr/bin/perl
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
#
# Licensed under the terms of the GNU GPL v3, or any later version.

use strict;
use warnings;
use utf8;

my $acpi;
my $acpi_info;
my $status;
my $percent;
my $full_capacity_percent;
my $full_text;
my $short_text;
my $bat_number = $ENV{BLOCK_INSTANCE} || 0;

# read the first line of the "acpi" command output for battery status
open (ACPI, "acpi -b | grep -E \"Battery $bat_number\" |") or die;
$acpi = <ACPI>;
close(ACPI);

# read battery info for last full capacity
open (ACPI_INFO, "acpi -i | grep -E \"Battery $bat_number\" | grep 'last full capacity' |") or die;
$acpi_info = <ACPI_INFO>;
close(ACPI_INFO);

# extract last full capacity percentage
if ($acpi_info =~ /last full capacity (\d+) mAh = (\d+)%/) {
    $full_capacity_percent = $2;
}

# fail on unexpected output
if ($acpi !~ /: (\w+), (\d+)%/) {
    die "$acpi\n";
}

$status = $1;
$percent = $2;
$full_text = "$percent%";

# add full capacity percentage if available
if (defined $full_capacity_percent) {
    $full_text .= " ($full_capacity_percent%)";
}

if ($status eq 'Discharging') {
    $full_text .= ' DIS';
} elsif ($status eq 'Charging') {
    $full_text .= ' CHR';
}

$short_text = $full_text;

if ($acpi =~ /(\d\d:\d\d):/) {
    $full_text .= " ($1)";
}

# print text
print "$full_text\n";
print "$short_text\n";

# consider color and urgent flag only on discharge
if ($status eq 'Discharging') {

    if ($percent < 20) {
        print "";
    } elsif ($percent < 40) {
        print "";
    } elsif ($percent < 60) {
        print "";
    } elsif ($percent < 85) {
        print "";
    }

    if ($percent < 5) {
        exit(33);
    }
}

exit(0);
